name: Selenium-webdriver JS

on:
  deployment_status:

jobs:
  build:
    name: test-${{matrix.os}}-${{matrix.node-version}}
    defaults:
      run:
        working-directory: ./test/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'

    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests in US
        run: npm run test
